### ISSUE TITLE
Query having a missing parameter

### ISSUE THREAD

**Issue by BEZEI2K** [orchestrate-io/gorc2#10]
demo_playstation?limit=20&query=%!+(MISSING)%!D(MISSING)arksiders%!+(MISSING)OR+%!A(MISSING)dventure+Time%!A(MISSING)+The+Secret+of+the+Nameless+Kingdom%!+(MISSING)OR+%!B(MISSING)randish%!A(MISSING)+The+Dark+Revenant%!+(MISSING)%!+(MISSING)AND+%!+(MISSING)value.Title%!A(MISSING)+%!A(MISSING)a%!A(MISSING)+%! (MISSING)[]}

that is the query I am receiving in the returned iterator.

**Comment by liquidgecka** [comment]
I think we dug into the guts of this one right? Sorry I didn't notice the issue until just now. =)
